name: Fetch Repository Details
description: Fetch repository and owner details 

runs:
  using: 'composite'
  steps:
    - uses: actions/github-script@v4
      id: fetch-repo-details
      with:
        script: |
          const query = `query($owner:String!, $name:String!) {
            repository(owner:$owner, name:$name) {
              name
              description
              owner {
                login
                ... on User {
                  name
                }
                ... on Organization {
                  name
                }
              }
            }
          }`;
          const variables = {
            owner: context.repo.owner,
            name: context.repo.repo
          }
          const result = await github.graphql(query, variables)
          console.log(result)
          return result
