name: Fetch Repository Details
description: Fetch repository and owner details 

outputs:
  details:
    description: "The fetched details"
    value: $INFO
  repo_name:
    description: "name of repository"
    value: $REPO_NAME
  repo_description:
    description: "description of repository"
    value: $REPO_DESCRIPTION
  repo_owner_name:
    description: "The owner of repository"
    value: $REPO_OWNER_NAME

runs:
  using: 'composite'
  steps:
    - uses: actions/github-script@v4
      id: fetch-repo-details
      with:
        script: |
          const query = `query($owner:String!, $name:String!) {
            repository(owner:$owner, name:$name) {
              name
              description
              owner {
                login
                ... on User {
                  name
                }
                ... on Organization {
                  name
                }
              }
            }
          }`;
          const variables = {
            owner: context.repo.owner,
            name: context.repo.repo
          }
          const result = await github.graphql(query, variables)
          console.log(result)
          return result

    - run: |
        echo $INFO | jq -r '.repository.name' >> $REPO_NAME
        echo $INFO | jq -r '.repository.owner.name' >> $REPO_OWNER_NAME
        echo $INFO | jq -r '.repository.description' >> $REPO_DESCRIPTION
      shell: bash
      env:
        INFO: ${{ steps.fetch-repo-details.outputs.result }}
