name: Rename Template Solution
description: 'Renames a template solution with all projects and references, and applies a { inputs.prefix } to rootnamespace and packageId'
runs:
  using: 'composite'
  steps:
    - name: Rename solution file
      run: |
        echo "Renaming ${{ inputs.template_name }}.sln to ${{ inputs.new_name }}.sln"
        mv ${{ inputs.template_name }}.sln ${{ inputs.new_name }}.sln
        sed -i "s/${{ inputs.template_name }}/${{ inputs.new_name }}/g" ${{ inputs.new_name }}.sln
      shell: bash

    - name: Rename project files and directories
      uses: actions/github-script@v4
      with:
        script: |
          const { execSync } = require('child_process');
      
          const templateName = process.env.INPUT_TEMPLATE_NAME;
          const newName = process.env.INPUT_NEW_NAME;

          execSync(`mkdir -p ./src/${templateName} ./tests/${templateName}.Tests`);

          const findDirs = execSync(`find . -type d -name "${templateName}*"`).toString().trim().split('\n');
          findDirs.forEach(dir => {
            const newDir = dir.replace(templateName, newName);
            execSync(`mv "${dir}" "${newDir}"`);
            execSync(`find "${newDir}" -type f -exec sed -i "s/${templateName}/${newName}/g" {} +`);
          });

          const findFiles = execSync(`find . -type f -name "${templateName}*.csproj"`).toString().trim().split('\n');
          findFiles.forEach(file => {
            const newFile = file.replace(templateName, newName);
            execSync(`mv "${file}" "${newFile}"`);
            execSync(`sed -i "s/${templateName}/${newName}/g" "${newFile}"`);
          });
      env:
        INPUT_TEMPLATE_NAME: ${{ inputs.template_name }}
        INPUT_NEW_NAME: ${{ inputs.new_name }}

    - name: Rename references in project files
      run: |
        find . -type f -name "*.csproj" -exec sed -i "s/${{ inputs.template_name }}/${{ inputs.new_name }}/g" {} \;
        find . -type f -name "*.props" -exec sed -i "s/${{ inputs.template_name }}/${{ inputs.new_name }}/g" {} \;
        find . -type f -name "*.targets" -exec sed -i "s/${{ inputs.template_name }}/${{ inputs.new_name }}/g" {} \;
        find . -type f -name "*.csproj" -exec sed -i "s/<Prefix>.*<\/Prefix>/<Prefix>${{ inputs.prefix }}<\/Prefix>/g" {} \;
        find . -type f -name "*.csproj" -exec sed -i "s/<PackageId>.*<\/PackageId>/<PackageId>${{ inputs.prefix }}.${{ inputs.new_name }}<\/PackageId>/g" {} \;
        find . -type f -name "*.csproj" -exec sed -i "s/<Authors>.*<\/Authors>/<Authors>${{ inputs.authors }}<\/Authors>/g" {} \;
        find . -type f -name "*.csproj" -exec sed -i "s/<RepositoryUrl>.*<\/RepositoryUrl>/<RepositoryUrl>${{ inputs.repository_url }}<\/RepositoryUrl>/g" {} \;
        find . -type f -name "*.csproj" -exec sed -i "s/<Description>.*<\/Description>/<Description>${{ inputs.description}}<\/Description>/g" {} \;
        find . -type f -name "*.props" -exec sed -i "s/<Prefix>.*<\/Prefix>/<Prefix>${{ inputs.prefix }}<\/Prefix>/g" {} \;
        find . -type f -name "*.props" -exec sed -i "s/<PackageId>.*<\/PackageId>/<PackageId>${{ inputs.prefix }}.${{ inputs.new_name }}<\/PackageId>/g" {} \;
        find . -type f -name "*.props" -exec sed -i "s/<Authors>.*<\/Authors>/<Authors>${{ inputs.authors }}<\/Authors>/g" {} \;
        find . -type f -name "*.props" -exec sed -i "s/<RepositoryUrl>.*<\/RepositoryUrl>/<RepositoryUrl>${{ inputs.repository_url }}<\/RepositoryUrl>/g" {} \;
        find . -type f -name "*.props" -exec sed -i "s/<Description>.*<\/Description>/<Description>${{ inputs.description}}<\/Description>/g" {} \;
      shell: bash

    

inputs:
  template_name:
    description: 'The new name for the solution'
    required: true
  new_name:
    description: 'The new name for the solution'
    required: true
  authors:
    description: 'Authors for the package'
    required: true
  description:
    description: 'Description for the package'
    required: true
  repository_url:
    description: 'Repository URL for the package'
    required: true
  prefix:
    description: 'Prefix for rootnamespace and packageId'
    required: false
    default: 'PREFIX'