name: Set Secrets

on:
  workflow_call:
    inputs:
      secrets:
        description: 'String of secrets to set, separated by commas'
        required: true
        type: string

jobs:
  set_secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Set Secrets
        run: |
          IFS=',' read -r -a secrets_array <<< "${{ inputs.secrets }}"
          for secret in "${secrets_array[@]}"
          do
            key=$(echo $secret | cut -f1 -d',')
            value=$(echo $secret | cut -s -f2 -d':')
            if [ -z "$value" ]; then
              value=""
            fi
            gh secret set $key --body "$value"
          done
