name: Replace Project Name

on:
  workflow_call:
    inputs:
      placeholder:
        description: 'The placeholder to replace'
        required: true
        type: string
      new_name:
        description: 'The new name to replace the placeholder with'
        required: true
        type: string

jobs:
  replace_project_name:
    runs-on: ubuntu-latest

    steps:
      - name: Replace placeholder in files
        run: |
          PLACEHOLDER="${{ inputs.placeholder }}"
          NEW_NAME="${{ inputs.new_name }}"
          find . -type f -exec sed -i "s/$PLACEHOLDER/$NEW_NAME/g" {} +

      - name: Rename directories
        run: |
          PLACEHOLDER="${{ inputs.placeholder }}"
          NEW_NAME="${{ inputs.new_name }}"
          find . -type d -name "*$PLACEHOLDER*" -exec bash -c 'mv "$0" "${0//$PLACEHOLDER/$NEW_NAME}"' {} \;
