name: Publish to NuGet.org
description: 'Publishes a .NET package to NuGet.org'
runs:
  using: 'composite'
  steps:
    - name: Download packaged artifacts
      uses: actions/download-artifact@v3
      with:
        name: package-output

    - name: Publish to NuGet.org
      run: dotnet nuget push ./nupkg/*.nupkg -k ${{ inputs.nuget_api_key }} -s https://api.nuget.org/v3/index.json
      shell: bash

inputs:
  nuget_api_key:
    description: 'NuGet API key'
    required: true
