name: Create Branch

on:
  workflow_call:
    inputs:
      name:
        description: 'The name of the branch to create'
        required: true
        type: string

jobs:
  create_dev_branch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create '${{ inputs.name }}' branch
        run: |
          git checkout -b ${{ inputs.name }}
          git push origin ${{ inputs.name }}
