name: Replace Placeholders

on: workflow_call
inputs:
      project-name:
        description: 'Name of the project'
        required: true
        default: 'ProjectName'
      description:
        description: 'Project description'
        required: false
      version:
        description: 'Start version'
        required: true
        default: '1.0.0'
      prefix:
        description: 'Prefix for namespace and Nuget package'
        required: true
      tags:
        description: 'Tags for the package separated by semicolons'
        required: false

jobs:
  replace_placeholders:
    runs-on: ubuntu-latest

    steps:
      - name: Replace placeholders in Directory.Build.props
        run: |
          PROJECT_NAME=${{ steps.project.outputs.name }}
          sed -i "s/<PackageId><\/PackageId>/<PackageId>${{ inputs.project-name }}<\/PackageId>/" Directory.Build.props
          sed -i "s/<Authors><\/Authors>/<Authors>${GITHUB_ACTOR}<\/Authors>/" Directory.Build.props
          sed -i "s/<Description><\/Description>/<Description>${{ inputs.description }}<\/Description>/" Directory.Build.props
          sed -i "s/<PackageTags><\/PackageTags>/<PackageTags>${{ inputs.tags }}<\/PackageTags>/" Directory.Build.props
          sed -i "s/<RepositoryUrl><\/RepositoryUrl>/<RepositoryUrl>https:\/\/github.com\/${{ github.repository }}<\/RepositoryUrl>/" Directory.Build.props
