name: Replace Placeholders in Directory.Build.Props

on:
  workflow_call:
    inputs:
      project-name:
        description: 'Name of the project'
        required: true
        type: string
        default: 'ProjectName'
      description:
        description: 'Project description'
        required: false
        type: string
      version:
        description: 'Start version'
        required: true
        default: '1.0.0'
        type: string
      prefix:
        description: 'Prefix for namespace and Nuget package'
        required: true
        type: string
      tags:
        description: 'Tags for the package separated by semicolons'
        required: false
        type: string

jobs:
  replace_placeholders:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Replace placeholders in Directory.Build.props
        run: |
          sed -i "s/<PackageId><\/PackageId>/<PackageId>${{ inputs['project-name'] }}<\/PackageId>/" Directory.Build.props
          sed -i "s/<Authors><\/Authors>/<Authors>${{ github.actor }}<\/Authors>/" Directory.Build.props
          sed -i "s/<Description><\/Description>/<Description>${{ inputs.description }}<\/Description>/" Directory.Build.props
          sed -i "s/<PackageTags><\/PackageTags>/<PackageTags>${{ inputs.tags }}<\/PackageTags>/" Directory.Build.props
          sed -i "s/<RepositoryUrl><\/RepositoryUrl>/<RepositoryUrl>https:\/\/github.com\/${{ github.repository }}<\/RepositoryUrl>/" Directory.Build.props
