name: Set Secrets

on:
  workflow_call:
    inputs:
      secrets:
        description: 'Array of secrets to set'
        required: true
        type: array

jobs:
  set_secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Set Secrets
        run: |
          for secret in "${{ inputs.secrets[@] }}"
          do
            key=$(echo $secret | cut -f1 -d':')
            value=$(echo $secret | cut -s -f2 -d':')
            if [ -z "$value" ]; then
              value=""
            fi
            gh secret set $key --body "$value"
          done
